### ISSUE TITLE
L12.ipynb runtime 18 minutes

### ISSUE THREAD

**Issue by JosephKarpinski** [mlittmancs/great_courses_ml#10]
Wow. 
Took 18 minutes to run with no indication it was still running. 
Could be confusing to a lot of people.

<img width="1136" alt="wow_18_minutes" src="https://user-images.githubusercontent.com/37123616/99280793-bca4e900-27ff-11eb-9ea9-67e92021ef08.png">

**Comment by mlittmancs** [comment]
Thanks for the heads up. I'll try to make the comment provide more of a
warning.
