### ISSUE TITLE
L01aux.ipynb throws errors due to depreciated code.

### ISSUE THREAD

**Issue by X3RV** [mlittmancs/great_courses_ml#64]
Hello.  It would appear that L01aux.ipynb contains depreciated code in the import section.  

from keras.preprocessing import image

Causing it to throw errors.

I believe the solution is:
from tensorflow.keras.preprocessing import image

Good day.

**Comment by mlittmancs** [comment]
Thanks for the heads up!

I went through and updated a bunch of the library references. Can you take
a look and see if it's back on track?
