### ISSUE TITLE
L05.ipynb import statement fails

### ISSUE THREAD

**Issue by SpencerGreene** [mlittmancs/great_courses_ml#65]
```
import numpy as np
from keras.preprocessing import image

img = image.load_img("greenML.png")
```

yields the following error on Colab, as of 2023.08.29:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-f23b0203c5c4>](https://dluhyyp4vhw-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230824-060124-RC01_559862993#) in <cell line: 5>()
      3 from keras.preprocessing import image
      4 
----> 5 img = image.load_img("greenML.png")
      6 
      7 display(img)

AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
```

(There is a solution in https://stackoverflow.com/questions/72383347/how-to-fix-it-attributeerror-module-keras-preprocessing-image-has-no-attribu -- tested and it does work correctly with this instead:

```import keras.utils as image```

**Comment by mlittmancs** [comment]
Thanks for diving into this! I'm not able to reproduce your error, however. I have seen this error in other files and there's a fix I'd be using. But, for some reason, this file doesn't complain. Anyhow, I'll do the change I did elsewhere and maybe it'll straighten things out?

**Comment by mlittmancs** [comment]
The changes I made seem to be running fine for me. I'll upload the revised version.

**Comment by SpencerGreene** [comment]
It works for me now too.  Very curious that it wasn't reproducible - I thought that was the point of colab? - but thanks for looking into it!

**Comment by mlittmancs** [comment]
Yeah, colab turned out to be more unreliable than I thought it would be.
They frequently introduce changes to the libraries that break my code.
That's some of what you are seeing. The other big challenge is that
archived datasets change their format.
