### ISSUE TITLE
L05qs.ipynb URL gives 404 not found

### ISSUE THREAD

**Issue by SpencerGreene** [mlittmancs/great_courses_ml#66]
The line 
`!wget https://github.com/mlittmancs/great_courses_ml/raw/master/greenML.png`

in this file should be 
`!wget https://github.com/mlittmancs/great_courses_ml/raw/master/imgs/greenML.png`

**Comment by mlittmancs** [comment]
Great catch, thanks! Uploading now... (I also changed the image loader like in the other file.)
