### ISSUE TITLE
L11.ipynb array type issue

### ISSUE THREAD

**Issue by SpencerGreene** [mlittmancs/great_courses_ml#69]
This section of L11:
```
from sklearn.datasets import fetch_openml
data = fetch_openml(name='mnist_784')

import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.1)
X_train, X_test, y_train, y_test = train_test_split(X_test, y_test, test_size=0.33)
```
is creating the X variables as `pandas.core.frame.DataFrame` and y as `pandas.core.series.Series`, instead of numpy arrays. This then causes errors in the kmeans function:
```  
   d = len(data[0])  # THROWS!
``` 
and 
```
   centers = data[[random.randint(0,n-1) for i in range(k)]]  # THROWS!
```
The DataFrame apparently doesn't index that way?

I tried to fix it with this:
```
X_train, X_test = np.array(X_train), np.array(X_test)
y_train, y_test = np.array(y_train), np.array(y_test)
```
and that _mostly_ works, until it reaches here
```
      mode = stats.mode(labs[train_centerids == i]).mode   # THROWS!
      if len(mode) > 0: clust_labs[i] = mode[0]
```
This may be different issue - though perhaps they're both related to a new library version that changes how things are interpreted?  This line has several issues: 1) the stats.mode function doesn't work on an array of string inputs, it only wants an array of numerics; 2) the function is returning a ModeResult not an array.

I don't know enough about these libraries - seems like it's resolving a different mode function than the one that was intended, because something in the environment changed. Is there a way to force colab to stick with a known version?

Or: since you mentioned that a previous issue was not reproducible: is there something I need to do in my own colab config to make sure it uses the same versions that were intended when the notebook was created?

**Comment by SpencerGreene** [comment]
UPDATE: for the first issue, another (probably better) solution appears to be:
```
data = fetch_openml(name='mnist_784', as_frame=False)
```

**Comment by SpencerGreene** [comment]
UPDATE^2: here is what works for me for the mode calculation:

```
      mode = stats.mode(pd.Series(labs[train_centerids == i]).astype(int)).mode
      if not pd.isna(mode): clust_labs[i] = mode 
```

1. `labs` is now an `ndarray` so it has to cast to Series to use the `== i` filter.
2. The result of that filter seems to be a Series of Series, so cast back to `astype(int)`.
3. In the next line, the original accessed `mode.mode` as an array with value in [0] and presumably count in [1]. I'm seeing `mode.mode` as a scalar that contains value or NaN, and `mode.count` as the count.

There must be a better way?

**Comment by SpencerGreene** [comment]
UPDATE^3: in the next section the import seems to have changed:
```
# from keras.preprocessing.image import array_to_img   # FAILS
from keras_preprocessing.image import array_to_img.    # WORKS
```

**Comment by SpencerGreene** [comment]
With these three changes (in the three UPDATEs) everything works!

**Comment by mlittmancs** [comment]
That's great, thanks! I switched it to np.isnan since I hadn't imported
pandas.

**Comment by mlittmancs** [comment]
Nice one!

**Comment by mlittmancs** [comment]
For UPDATE^3, I fixed it a little differently to make it consonant with how I was fixing similar issues in other files. With your help, this one seems to be up and running again. Thank you!
