### ISSUE TITLE
YAVI (yet another version issue): L15.ipynb

### ISSUE THREAD

**Issue by SpencerGreene** [mlittmancs/great_courses_ml#73]
To get it to work I had to do this:

```
!pip install keras=='2.13.1'
!pip install Keras-Preprocessing
```

Because the notebook has persistence it seems like the experience from "cold" - first time downloading and using - is tricky to reproduce. After a fix sometimes the original version also starts working - because the environment has the new package or etc and is not behaving like it was when cold. But trust me, for a new user the 2.8.0 does fail.

**Comment by mlittmancs** [comment]
Thanks! (I didn't end up using the second install, though.)
