### ISSUE TITLE
L05.ipynb ERROR 404: Not Found.

### ISSUE THREAD

**Issue by JosephKarpinski** [mlittmancs/great_courses_ml#9]
L05.ipynb ERROR 404: Not Found.

--2020-11-14 23:23:13--  https://github.com/mlittmancs/great_courses_ml/raw/master/greenML.png
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-14 23:23:13 ERROR 404: Not Found.

This is wrong:
!wget https://github.com/mlittmancs/great_courses_ml/raw/master/greenML.png

It should be:
!wget https://github.com/mlittmancs/great_courses_ml/raw/master/imgs/greenML.png

**Comment by JosephKarpinski** [comment]
Another error:

--2020-11-14 23:46:53--  https://github.com/mlittmancs/great_courses_ml/raw/master/forest.jpg
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-14 23:46:53 ERROR 404: Not Found.

This is wrong:
!wget https://github.com/mlittmancs/great_courses_ml/raw/master/forest.jpg

It should be:
!wget https://github.com/mlittmancs/great_courses_ml/raw/master/imgs/forest.jpg

**Comment by mlittmancs** [comment]
Thank you, good catch! (There was a last-minute rearrangement of files and
it looks like I missed some changes.)

I think it's fixed now, yes?

**Comment by mlittmancs** [comment]
Ok, I ran a check myself and it looks ok!
